/**
 * Copyright (c) 2026 OpenAgent Team
 * Licensed under the MIT License
 */


import fs from "fs/promises";
import path from "path";
import { createSpinner, success } from "./ui.js";

const IGNORED_DIRS = new Set([
  "node_modules", ".git", "dist", "build", ".next", ".nuxt",
  "__pycache__", ".venv", "venv", ".env", "coverage", ".turbo",
  ".cache", ".output", ".vercel", ".openagent",
]);

const IGNORED_EXTENSIONS = new Set([
  ".lock", ".png", ".jpg", ".jpeg", ".gif", ".svg", ".ico",
  ".woff", ".woff2", ".ttf", ".eot", ".mp4", ".mp3", ".pdf",
  ".zip", ".tar", ".gz", ".map",
]);

interface FileEntry {
  relativePath: string;
  isDir: boolean;
  size: number;
}

async function scanDirectory(root: string, relativeTo: string = root): Promise<FileEntry[]> {
  const entries: FileEntry[] = [];

  const items = await fs.readdir(root, { withFileTypes: true });

  for (const item of items) {
    if (item.name.startsWith(".") && item.name !== ".env.example") continue;
    if (IGNORED_DIRS.has(item.name)) continue;

    const fullPath = path.join(root, item.name);
    const relPath = path.relative(relativeTo, fullPath);

    if (item.isDirectory()) {
      entries.push({ relativePath: relPath, isDir: true, size: 0 });
      const subEntries = await scanDirectory(fullPath, relativeTo);
      entries.push(...subEntries);
    } else {
      const ext = path.extname(item.name).toLowerCase();
      if (IGNORED_EXTENSIONS.has(ext)) continue;

      const stat = await fs.stat(fullPath);
      entries.push({ relativePath: relPath, isDir: false, size: stat.size });
    }
  }

  return entries;
}

async function readFileIfExists(filePath: string): Promise<string | null> {
  try {
    return await fs.readFile(filePath, "utf-8");
  } catch {
    return null;
  }
}

function buildFileTree(entries: FileEntry[]): string {
  const lines: string[] = [];
  for (const entry of entries) {
    const depth = entry.relativePath.split(path.sep).length - 1;
    const indent = "  ".repeat(depth);
    const icon = entry.isDir ? "📁" : "📄";
    lines.push(`${indent}${icon} ${path.basename(entry.relativePath)}`);
  }
  return lines.join("\n");
}

export async function scanProject(projectPath: string): Promise<string> {
  const spinner = createSpinner("Scanning project...");
  spinner.start();

  const entries = await scanDirectory(projectPath);
  const fileTree = buildFileTree(entries);

  spinner.text = "Reading config files...";

  const packageJson = await readFileIfExists(path.join(projectPath, "package.json"));
  const tsconfigJson = await readFileIfExists(path.join(projectPath, "tsconfig.json"));
  const readme = await readFileIfExists(path.join(projectPath, "README.md"));


  spinner.text = "Generating OPENAGENT.MD...";

  let md = `# Project Context\n\n`;
  md += `> Auto-generated by OpenAgent. Updated dynamically as the agent works.\n\n`;

  const projectName = path.basename(projectPath);
  md += `## Overview\n`;
  md += `- **Project**: ${projectName}\n`;
  md += `- **Path**: ${projectPath}\n`;
  md += `- **Scanned**: ${new Date().toISOString()}\n\n`;

  if (packageJson) {
    try {
      const pkg = JSON.parse(packageJson);
      md += `## Tech Stack\n`;
      md += `- **Name**: ${pkg.name ?? projectName}\n`;
      md += `- **Version**: ${pkg.version ?? "N/A"}\n`;
      if (pkg.description) md += `- **Description**: ${pkg.description}\n`;

      const allDeps = { ...pkg.dependencies, ...pkg.devDependencies };
      const depNames = Object.keys(allDeps);
      if (depNames.length > 0) {
        md += `- **Key Dependencies**: ${depNames.slice(0, 20).join(", ")}`;
        if (depNames.length > 20) md += ` (+${depNames.length - 20} more)`;
        md += "\n";
      }

      if (pkg.scripts) {
        md += `\n### Scripts\n`;
        for (const [name, cmd] of Object.entries(pkg.scripts)) {
          md += `- \`${name}\`: \`${cmd}\`\n`;
        }
      }
      md += "\n";
    } catch {
      // Invalid JSON, skip
    }
  }

  if (tsconfigJson) {
    md += `## TypeScript Config\n`;
    md += `\`\`\`json\n${tsconfigJson.slice(0, 500)}\n\`\`\`\n\n`;
  }

  md += `## File Structure\n`;
  md += `\`\`\`\n${fileTree}\n\`\`\`\n\n`;

  const codeFiles = entries.filter(e => !e.isDir);
  md += `## Stats\n`;
  md += `- **Files**: ${codeFiles.length}\n`;
  md += `- **Directories**: ${entries.filter(e => e.isDir).length}\n`;
  md += `- **Total size**: ${(codeFiles.reduce((sum, e) => sum + e.size, 0) / 1024).toFixed(1)}KB\n\n`;

  if (readme) {
    const trimmedReadme = readme.length > 1000 ? readme.slice(0, 1000) + "\n...(truncated)" : readme;
    md += `## README\n${trimmedReadme}\n\n`;
  }

  md += `## Recent Changes\n_No changes tracked yet. OpenAgent will update this as it works._\n\n`;
  md += `## Progress\n_No progress tracked yet._\n\n`;

  md += `---\n*Last updated by OpenAgent: ${new Date().toISOString()}*\n`;

  const outputPath = path.join(projectPath, "OPENAGENT.MD");
  await fs.writeFile(outputPath, md, "utf-8");

  spinner.succeed("Project scanned");
  success(`Created OPENAGENT.MD (${(md.length / 1024).toFixed(1)}KB)`);

  return md;
}
